### ISSUE TITLE
python脚本可以读取，但是c++编译代码不行

### ISSUE THREAD

**Issue by qahehe** [ldsaiyan/EventLogPersist#1]
![image](https://user-images.githubusercontent.com/25258443/223599216-584b92ea-7559-4e6a-b311-85275bdc2e15.png)
使用python的B脚本可以把事件日志读取出来上线，但是vs编译和g++编译的exe报错了，不知道什么原因读不出来。

**Comment by ldsaiyan** [comment]
#define BUFFER_SIZE 1024  改大一点试试呢？ #define BUFFER_SIZE 1024 * 2 这样子

**Comment by qahehe** [comment]
> #define BUFFER_SIZE 1024 改大一点试试呢？ #define BUFFER_SIZE 1024 * 2 这样子
大佬你这个解决方法可以了，这是什么原理呢，是开辟的内存空间不够导致的吗？
